### ISSUE TITLE
Symbol is not injected after Babel

### ISSUE THREAD

**Issue by luwes** [rollup/rollup-plugin-inject#20]
Thanks for this great plugin!
We ran into an issue with our rollup config that first runs Babel and then the inject plugin but in some cases the polyfill is not injected correctly.

```js
    inject({
        exclude: [
            'node_modules/**/native-promise-only/**',
            'node_modules/**/es6-symbol/**'
        ],
        modules: {
            'Promise': 'native-promise-only',
            'Symbol': 'es6-symbol'
        }
    }),
```

Outputted code:

Didn't get injected here, helper from Babel plugin.

```js
function _iterableToArray(iter) {
  if (Symbol.iterator in Object(iter) || Object.prototype.toString.call(iter) === "[object Arguments]") return Array.from(iter);
}
```

Snippet with proper output.

```js
    var m = typeof es6Symbol === "function" && o[es6Symbol.iterator], i = 0;
    if (m) return m.call(o);
```

**Comment by btd** [comment]
@luwes i think this is really issue with the order of plugin. You can try to inject before applying babel or even split injecting if you are applying some stage plugins for babel (because rollup uses acorn). It would be nice to get some example file and config to see.

**Comment by luwes** [comment]
Thanks guys, I tried changing the order but it unfortunately didn't have an effect.
I'll try to set up a test repo and let you know.

**Comment by luwes** [comment]
Seems that the include/exclude filters out id's with `\0`.
And this id is filtered out before the injection can happen
`\u0000rollupPluginBabelHelpers`

**Comment by luwes** [comment]
This fixes the problem but not sure this is something that should go in.
https://github.com/luwes/rollup-plugin-inject/commit/d93d4d7c844ddd8330a916a7e4849ab184f7add8

**Comment by Andarist** [comment]
From what I understand the `\0` convention is used exactly to restrict the "virtual module" access. If this is true then this is really an issue with rollup's convention and not with the rollup-plugin-babel itself. I might be wrong about this though.

Maybe `rollup-plugin-inject` could introduce an option (or even switch to that behaviour entirely) to inject in the later phase of rollup - generating or smth (after modules are already concatenated) - instead of using the transform phase. Although not sure if source manipulation is allowed in later phases.

Also what I can recommend (and Im planning to recommend through validation checks in rollup-plugin-babel itself in the future) is using runtime helpers and that would alleviate your problem. You can check out how to configure this here:
https://github.com/andreypopp/react-textarea-autosize/blob/e3d763fb94b9b62ae14ca9cb5f2f7acf8f827228/rollup.config.js#L40-L49

Keep in mind that you'd have to include `node_modules ` in rollup-plugin-inject configuration (or at least include `@babel/runtime` module)

**Comment by luwes** [comment]
@Andarist thanks for your reply. I tried adding the runtime helpers but it's introducing a new error.

<img width="522" alt="screen shot 2018-10-17 at 8 42 46 am" src="https://user-images.githubusercontent.com/360826/47086946-cd31a200-d1e8-11e8-82b6-13b0fe7886ce.png">

This is the code Babel generates:

```
function _typeof2(obj) {
  if (typeof es6Symbol === "function" && _typeof$$1(es6Symbol.iterator) === "symbol") {
    _typeof2 = function _typeof2(obj) {
      return _typeof$$1(obj);
    };
  } else {
    _typeof2 = function _typeof2(obj) {
      return obj && typeof es6Symbol === "function" && obj.constructor === es6Symbol && obj !== es6Symbol.prototype ? "symbol" : _typeof$$1(obj);
    };
  }

  return _typeof2(obj);
}

function _typeof$$1(obj) {
  if (typeof es6Symbol === "function" && _typeof2(es6Symbol.iterator) === "symbol") {
    _typeof$$1 = function _typeof$$1(obj) {
      return _typeof2(obj);
    };
  } else {
    _typeof$$1 = function _typeof$$1(obj) {
      return obj && typeof es6Symbol === "function" && obj.constructor === es6Symbol && obj !== es6Symbol.prototype ? "symbol" : _typeof2(obj);
    };
  }

  return _typeof$$1(obj);
}
```

**Comment by Andarist** [comment]
Oh right, this is a known issue and Im not sure what can be done about it. Would excluding the @babel/plugin-transform-typeof-symbol plugin or excluding that @babel/runtime helper (typeof) help your case? Or do u have to inject to it?

**Comment by luwes** [comment]
Great, excluding `'node_modules/@babel/**',` from rollup-plugin-babel did the trick!
Thank you.

**Comment by luwes** [comment]
@btd so far Babel only works with a polyfill library `corejs` to do something similar than this inject plugin. And we prefer standalone lightweight polyfills that don't pollute the global namespace if possible.

I still think this is more correct, although not the nicest code. https://github.com/luwes/rollup-plugin-inject/commit/d93d4d7c844ddd8330a916a7e4849ab184f7add8

If a plugin adds some extra code, subsequent plugins should be able to process that code as well.
