### ISSUE TITLE
inject after babel process

### ISSUE THREAD

**Issue by ritz078** [rollup/rollup-plugin-inject#3]
I am using babel to transpile `async/await` which needs the `regeneratorRuntime` method. So i want to inject it after the babel process is finished and `regeneratorRuntime` method is present in the file. Its not injected because its not present anywhere in the original file. Is there any way to do that ?

I am using grunt-rollup.
```js
rollup: {
    options: {
        format: 'cjs',
        banner: "<%= meta.banner %>",
        plugins: [
            babel(),
            npm({
                jsnext: true,
                main: true
            }),
            commonjs({
                include: 'node_modules/**'
            }),
            inject({
                exclude: 'node_modules/**',
                modules: {
                    'regeneratorRuntime': path.resolve('src/js/vendor/regeneratorRuntime.es6')
                }
            }),
            replace(build)

        ]
    },
```

**Comment by Rich-Harris** [comment]
Sorry for the delay. Not quite sure what's going on here – the inject plugin should transform code that's already been transpiled by Babel (and the commonjs plugin, if applicable), because it follows them in the `plugins` array. Are you saying that `regeneratorRuntime` is present in the final bundle, but that it isn't imported? Can you share a repo that reproduces the issue? Thanks

**Comment by ritz078** [comment]
It has been fixed with babel update. It was being imported at the wrong place. i.e after it was being used. Thanks.
